inherit_from: .rubocop_todo.yml
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
Style/MixinUsage:
  Exclude:
    - 'bin/*'
